### ISSUE TITLE
can't load .bin model

### ISSUE THREAD

**Issue by ilya-ustinov** [linkfluence/fastText4j#1]
Loading .bin model failing with exception:

Exception in thread "main" java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.base/java.util.ArrayList.<init>(ArrayList.java:158)
	at fasttext.Dictionary.saveToMMap(Dictionary.java:145)
	at fasttext.FastText.saveAsMemoryMappedModel(FastText.java:812)
	at fasttext.FastText.main(FastText.java:868)

Is this problem about deserializing model?

**Comment by JadeCopet** [comment]
Hi, 

Commit 3ef6d98f1cff4af93fe644130c10add644f6dedb should fix the issue. The saveAsMemoryMappedModel method was not expecting a negative pruning size in the model which caused the exception on non-quantized models. 

Thank you for the feedback!

**Comment by dclong** [comment]
When will a new version be released?

**Comment by JadeCopet** [comment]
Hi, 

0.2.1 has just been released.
